doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: "mysql://root:db_password@127.0.0.1:3306/parser?serverVersion=mariadb-10.7.1&charset=utf8mb4"
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
