version: '3'

services:
  database:
      image: mariadb:10.7.1-focal
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - '0.0.0.0:3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: db_password
      volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:
